Repository Magenic/MAQS, pull requests merged in 2020-11, with the labels that each got.

#553 Bulk update NuGet packages 11-11-2020
  Framework/AppiumUnitTests/AppiumUnitTests.csproj
  Framework/BaseAppiumTest/BaseAppiumTest.csproj
  Framework/BaseDatabaseTest/BaseDatabaseTest.csproj
  Framework/BaseMongoTest/BaseMongoTest.csproj
  Framework/BaseSeleniumTest/BaseSeleniumTest.csproj
  Framework/BaseTestUnitTests/BaseTestUnitTests.csproj
  Framework/CompositeUnitTests/CompositeUnitTests.csproj
  Framework/DatabaseUnitTests/DatabaseUnitTests.csproj
  Framework/EmailUnitTests/EmailUnitTests.csproj
  Framework/FrameworkUnitTests/FrameworkUnitTests.csproj
  Framework/MongoDBUnitTests/MongoDBUnitTests.csproj
  Framework/SeleniumUnitTests/SeleniumUnitTests.csproj
  Framework/SpecFlowExtension/SpecFlowExtension.csproj
  Framework/SpecFlowExtensionNUnitTests/Features/DatabaseFeature.feature.cs
  Framework/SpecFlowExtensionNUnitTests/Features/EmailFeature.feature.cs
  Framework/SpecFlowExtensionNUnitTests/Features/ScenarioContextFeature.feature.cs
  Framework/SpecFlowExtensionNUnitTests/Features/SeleniumFeature.feature.cs
  Framework/SpecFlowExtensionNUnitTests/Features/TestObjectFeature.feature.cs
  Framework/SpecFlowExtensionNUnitTests/Features/WebServiceFeature.feature.cs
  Framework/SpecFlowExtensionNUnitTests/SpecFlowExtensionNUnitTests.csproj
  Framework/SpecFlowExtensionUnitTests/Features/DatabaseFeature.feature.cs
  Framework/SpecFlowExtensionUnitTests/Features/EmailFeature.feature.cs
  Framework/SpecFlowExtensionUnitTests/Features/ScenarioContextFeature.feature.cs
  Framework/SpecFlowExtensionUnitTests/Features/SeleniumFeature.feature.cs
  Framework/SpecFlowExtensionUnitTests/Features/TestObjectFeature.feature.cs
  Framework/SpecFlowExtensionUnitTests/Features/WebServiceFeature.feature.cs
  Framework/SpecFlowExtensionUnitTests/SpecFlowExtensionUnitTests.csproj
  Framework/Utilities/Utilities.csproj
  Framework/UtilitiesUnitTests/UtilitiesUnitTests.csproj
  Framework/WebServiceUnitTests/WebServiceUnitTests.csproj
Labels: dependencies

#566 Update C# MAQS Build.yml
  C# MAQS Build.yml
Labels: maintenance

#536 SoftAssert Expected Asserts
  Framework/BaseTest/BaseTest.cs
  Framework/BaseTest/SoftAssert.cs
  Framework/BaseTest/SoftAssertExpectedAsserts.cs
  Framework/BaseTestUnitTests/BaseFrameworkTests.cs
  Framework/UtilitiesUnitTests/SoftAssertUnitTests.cs
Labels: feature

#563 Adding Assertion to fix SonarLint 2699
  Framework/BaseTest/SoftAssert.cs
  Framework/Utilities/Helper/AssertionMethodAttribute.cs
Labels: enhancement

#565 Bulk NuGet package updates 11-19-2020
  Framework/BaseDatabaseTest/BaseDatabaseTest.csproj
  Framework/CompositeUnitTests/CompositeUnitTests.csproj
  Framework/FrameworkUnitTests/FrameworkUnitTests.csproj
  Framework/SeleniumUnitTests/SeleniumUnitTests.csproj
  Framework/SpecFlowExtension/SpecFlowExtension.csproj
  Framework/WebServiceUnitTests/WebServiceUnitTests.csproj
Labels: dependencies
