Repository Magenic/MAQS, pull requests merged in 2020-10, with the labels that each got.

#506 Updating NuGet packages
  Framework/SpecFlowExtension/SpecFlowExtension.csproj
  Framework/SpecFlowExtensionNUnitTests/SpecFlowExtensionNUnitTests.csproj
  Framework/SpecFlowExtensionUnitTests/SpecFlowExtensionUnitTests.csproj
Labels: dependabot, dependencies

#507 Adding documentation
  docs/MAQS_6/Debugging-Locally.md
  docs/MAQS_6/SourceLink.md
  docs/MAQS_6/_sidebar.md
Labels: documentation

#528 Allow lazy element send keys to be able to handle keys that cause navigation
  Framework/BaseSeleniumTest/Extensions/AbstractLazyIWebElement.cs
  Framework/SeleniumUnitTests/LazyElementUnitTests.cs
Labels: bug

#523 Fix Managerstore.md info on SeleniumDriver
  docs/MAQS_6/General/ManagerStore.md
Labels: documentation

#520 fix bugs in documentation
  docs/MAQS_6/Getting-Started.md
  docs/MAQS_6/_sidebar.md
Labels: documentation

#529 Updating NuGet Packages
  Framework/BaseDatabaseTest/BaseDatabaseTest.csproj
  Framework/BaseMongoTest/BaseMongoTest.csproj
  Framework/CompositeUnitTests/CompositeUnitTests.csproj
  Framework/FrameworkUnitTests/FrameworkUnitTests.csproj
  Framework/SeleniumUnitTests/SeleniumUnitTests.csproj
  Framework/SpecFlowExtension/SpecFlowExtension.csproj
  Framework/SpecFlowExtensionNUnitTests/SpecFlowExtensionNUnitTests.csproj
  Framework/SpecFlowExtensionUnitTests/SpecFlowExtensionUnitTests.csproj
  Framework/Utilities/Utilities.csproj
Labels: dependabot, dependencies

#508 Analyzer code change fixes
  Framework/AppiumUnitTests/AppiumUtilitiesTests.cs
  Framework/BaseSeleniumTest/Extensions/LazyElement.cs
  Framework/BaseSeleniumTest/SeleniumUtilities.cs
  Framework/BaseSeleniumTest/WebDriverFactory.cs
  Framework/BaseTest/BaseTest.cs
  Framework/BaseTestUnitTests/BaseFrameworkTests.cs
  Framework/EmailUnitTests/EmailUnitWithDriver.cs
  Framework/SeleniumUnitTests/SeleniumUnitTest.cs
  Framework/SeleniumUnitTests/SeleniumUtilsTest.cs
  Framework/SeleniumUnitTests/SeleniumWebElementTest.cs
  Framework/SeleniumUnitTests/WebDriverFactoryUnitTests.cs
  Framework/WebServiceUnitTests/WebServiceWithDriverPost.cs
Labels: maintenance

#530 Updating Axe to 2.0.0
  Framework/BaseSeleniumTest/BaseSeleniumTest.csproj
  Framework/BaseSeleniumTest/SeleniumUtilities.cs
Labels: dependencies
