Repository Magenic/MAQS, pull requests merged in 2020-09, with the labels that each got.

#467 Allow users to add or override a single config item
  Framework/Utilities/Helper/Config.cs
  Framework/UtilitiesUnitTests/ConfigUnitTests.cs
Labels: enhancement

#494 Removal of DotNetSeleniumExtras.PageObjects
  Framework/SpecFlowExtension/SpecFlowExtension.csproj
Labels: enhancement

#495 Upgrading NuGet Packages
  Framework/BaseAppiumTest/BaseAppiumTest.csproj
  Framework/BaseEmailTest/BaseEmailTest.csproj
  Framework/BaseSeleniumTest/BaseSeleniumTest.csproj
  Framework/SpecFlowExtension/SpecFlowExtension.csproj
Labels: dependencies

#498 Adding SauceLabs and SonarCloud badges
  README.md
Labels: documentation

#489 Updating .Net Core versions to supported versions for SpecFlowExtension
  Framework/SpecFlowExtension/SpecFlowExtension.csproj
Labels: feature
