Repository Magenic/MAQS, pull requests merged in 2021-02, with the labels that each got.

#623 Added Obsolete tag to EndTimer. Added Stop Timer
  Framework/Utilities/Performance/PerfTimerCollection.cs
Labels: enhancement

#634 6.2.1 Release
  Framework/BaseAppiumTest/BaseAppiumTest.csproj
  Framework/BaseCompositeTest/BaseCompositeTest.csproj
  Framework/BaseDatabaseTest/BaseDatabaseTest.csproj
  Framework/BaseEmailTest/BaseEmailTest.csproj
  Framework/BaseMongoTest/BaseMongoTest.csproj
  Framework/BaseSeleniumTest/BaseSeleniumTest.csproj
  Framework/BaseTest/BaseTest.csproj
  Framework/BaseWebServiceTest/BaseWebServiceTest.csproj
  Framework/SpecFlowExtension/SpecFlowExtension.csproj
  Framework/Utilities/Utilities.csproj
Labels: feature

#583 Removing obsolete SoftAssert method calls
  Framework/BaseTestUnitTests/BaseFrameworkTests.cs
  Framework/SeleniumUnitTests/SeleniumUnitTest.cs
  Framework/SeleniumUnitTests/SeleniumUtilsTest.cs
  Framework/UtilitiesUnitTests/FileLoggerUnitTests.cs
Labels: maintenance

#641 Release 6.2.2
  Framework/BaseAppiumTest/BaseAppiumTest.csproj
  Framework/BaseCompositeTest/BaseCompositeTest.csproj
  Framework/BaseDatabaseTest/BaseDatabaseTest.csproj
  Framework/BaseEmailTest/BaseEmailTest.csproj
  Framework/BaseMongoTest/BaseMongoTest.csproj
  Framework/BaseSeleniumTest/BaseSeleniumTest.csproj
  Framework/BaseTest/BaseTest.csproj
  Framework/BaseWebServiceTest/BaseWebServiceTest.csproj
  Framework/SpecFlowExtension/SpecFlowExtension.csproj
  Framework/Utilities/Utilities.csproj
Labels: enhancement
