Repository Magenic/MAQS, pull requests merged in 2021-04, with the labels that each got.

#696 Feature/appium page model
  Framework/AppiumUnitTests/App.config
  Framework/AppiumUnitTests/AppiumWinAppUnitTests.cs
  Framework/AppiumUnitTests/NotepadPageModel.cs
  Framework/BaseAppiumTest/BaseAppiumPageModel.cs
Labels: feature

#691 Performance Timer Collection Code Smells
  Framework/FrameworkUnitTests/Base.cs
  Framework/UtilitiesUnitTests/PerformanceUnitTests.cs
Labels: maintenance

#701 Add stack traces to soft assert logging
  Framework/BaseTest/SoftAssert.cs
Labels: enhancement

#690 SoftAssert Code Smells
  Framework/AppiumUnitTests/AppiumUtilitiesTests.cs
  Framework/AppiumUnitTests/BaseFrameworkTests.cs
  Framework/SeleniumUnitTests/SeleniumUnitTest.cs
  Framework/UtilitiesUnitTests/PerformanceUnitTests.cs
  Framework/UtilitiesUnitTests/SoftAssertUnitTests.cs
Labels: maintenance
